---

  - name: apt | cache | update
    apt: update_cache=yes
    when: do_install|bool

  - name: girder | deps | install
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - apt-utils
      - autoconf
      - build-essential
      - curl
      - cmake
      - g++
      - gfortran
      - git
      - gzip
      - libbz2-dev
      - libcppunit-dev
      - libexpat-dev
      - libffi-dev
      - libjpeg-dev
      - libpng-dev
      - libsqlite-dev
      - libssl-dev
      - libtool
      - m4
      - make
      - mongodb
      - ncurses-dev
      - openjdk-7-jdk
      - openjdk-7-jre-headless
      - openssh-client
      - openssh-server
      - python-pip
      - python-software-properties
      - python2.7-dev
      - rsync
      - sudo
      - tar
      - wget
    when: do_install|bool

  - name: girder | service | stop
    service:
        name: girder
        state: stopped
    ignore_errors: true
    when: stop_services|bool

  - name: girder | install root | delete
    file:
        path: "{{ girder_install_root }}"
        state: absent
    when: remove_install_root|bool

  - name: girder | data root | delete
    file:
        path: "{{ girder_data_root }}"
        state: absent
    when: remove_data_root|bool

  - name: girder | install parent | create
    file:
        path: "{{ girder_install_parent }}"
        state: directory
    when: do_install|bool

  - name: girder | data root | create
    file:
        path: "{{ girder_data_root }}"
        state: directory
        group: "{{ girder_group }}"
        owner: "{{ girder_user }}"
        mode: 0755
    when: do_install|bool


  - name: girder | repo | sync
    command: >
        rsync -avz --exclude=.git
        "{{ girder_git_work_dir }}/"
        "{{ girder_install_root }}"
    when: do_install|bool

  - name: Install editable version of girder
    pip:
      chdir: "{{ girder_install_root }}"
      extra_args: "-e"
      name: "."

  - name: Install frontend assets
    shell: "girder-install web"
    args:
      chdir: "{{ girder_install_root }}"

  - name: girder | conf | girder.local.cfg | generate
    template:
        src: girder.local.cfg.j2
        dest: "{{ girder_install_root }}/girder/conf/girder.local.cfg"
        mode: 0644
    when: do_install|bool

  - name: girder | conf | owner | set
    file:
        recurse: yes
        path: "{{ girder_install_root }}"
        owner: "{{ girder_user }}"
        group: "{{ girder_group }}"
    when: do_install|bool
